### ISSUE TITLE
Jekyll 3.0 not sure if the title is hitting correctly

### ISSUE THREAD

**Issue by Blumed** [fj/spicy-jekyll#6]
Thank you for taking the time to make this plugin it seems to be just what I need.

output from command line

```
found metadata for collection category: {"title"=>"Category", "refname"=>"one", "output"=>true} 
jekyll 3.0.0 | Error:  couldn't find a title
```

_config.yml

```
collections:
 category:
  title: Category
  refname: one
  output: true
```

I have two .md files in that collection and both have a title: Title. Why am I getting this build error?
It says the title in the meta data and each page has its own title in that collection.

Thanks in advance
